public class ProductCode {
    public static final String ONE = '001';
    public static final String TWO = '002';
    public static final String THREE = '003';
    public static final String FOUR = '004';
    public static final String FIVE = '005';
    public static final String SIX = '006';
    public static final String SEVEN = '007';
    public static final String EIGHT = '008';
    public static final String NINE = '009';
}